modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://www.github.com/xfacthd/buddingcrystals"
license="LGPL v2.1"

[[mods]]
    modId="buddingcrystals"
    version="${file.jarVersion}"
    displayName="BuddingCrystals"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
    logoFile="logo.png"
    credits="Thanks for this example mod goes to Java"
    authors="Love, Cheese and small house plants"
    description='''
    '''

[[dependencies.buddingcrystals]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buddingcrystals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buddingcrystals]]
    modId="dynamic_asset_generator"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="CLIENT"
